package com.walmart.move.nim.receiving.core.contract.prelabel.model;

import com.walmart.move.nim.receiving.core.model.DeliveryDocument;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * * Autogenerated class for GDM Delivery Documents
 *
 * @author sitakant
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class GDMDeliveryDocument {

  private String arrivedTimeStamp;
  private String countryCode;
  private String dcNumber;
  private List<DeliveryDocument> deliveryDocuments;
  private String deliveryLegacyStatus;
  private Long deliveryNumber;
  private String deliveryStatus;
  private String deliveryTypeCode;
  private String doorCloseUserId;
  private String doorOpenTimeStamp;
  private String doorOpenUserId;
  private Boolean hazmatInd;
  private String idmCompleteTimeStamp;
  private String lastUpdatedSealNumber;
  private String loadNumber;
  private String loadTypeCode;
  private Long numberOfPallets;
  private String scacCode;
  private String scheduledTimeStamp;
  private String sealNumber;
  private String trailerId;
  private String workingTimeStamp;
  private String workingUserId;
  private String doorNumber;
}
