deploy:
  stages:
    - name: prod-cell031
      approvers:
        groups:
          - "FLEXPLUS_RECEIVING"
          - "Tridents-SE"
      helm:
        values:
          env:
            DYNATRACE_ENABLED: true
            JAVA_OPTS: >-
              -Xms6144m
              -Xmx6144m
              -XX:+UseParNewGC
              -XX:+UseConcMarkSweepGC
              -XX:NewSize=3072M
              -XX:MaxMetaspaceSize=256M
              -Djsse.enableSNIExtension=true
              -Druntime.context.environmentType=prod
              -Druntime.context.environment=PROD
              -Druntime.context.appName=receiving-api
              -Druntime.context.system.property.override.enabled=true
              -Dscm.snapshot.enabled=true
              -Dscm.root.dir=/tmp/scm
              -Dscm.print.summary.onchange=true
              -Dscm.print.detailed.summary=true
              -Dspring.config.use-legacy-processing=true
              -Dspring.main.allow-bean-definition-overriding=true
              -Dcom.ibm.mq.cfg.useIBMCipherMappings=false
              -Dspring.config.additional-location=/etc/secrets/receiving-secrets.properties
              -DDATACENTER={{$.kittExec.currentCluster.zone}}
              -Dplatform=wcnp
              -DfacilityCountryCode=mx
              -DcellName=Cell031-USSouthCentral-USEast
              -Dio.strati.RuntimeContext=io.strati.impl.runtime.context.RuntimeContextEnv
              -Dcom.walmart.platform.metrics.impl.type=MICROMETER
              -Dcom.walmart.platform.txnmarking.otel.type=LOGGING
              -Dcom.walmart.platform.txnmarking.otel.port=80
              -Dcom.walmart.platform.txnmarking.otel.host=walmotelcol-deployment.walmotelcol.scus-stage-atracestore1.cluster.k8s.us.walmart.net
              -Dcom.walmart.platform.telemetry.otel.enabled=true
              -Dcom.walmart.platform.logging.profile=OTEL
              -Dspring.main.allow-circular-references=true

          metadata:
            labels:
              strati.appkey: ATLASRECEIVING
              strati.env: prod-mx
              wm.app: ATLASRECEIVING
              wm.env: prod-mx
            annotations:
              strati.passthroughUris: '[{"Path":"^/swagger-ui.html$"},{"Path":"^/.*"}]'
              sidecar.istio.io/inject: "true"
              traffic.sidecar.istio.io/excludeOutboundPorts: 8080
          min:
            cpu: 4000m
            memory: 8192Mi
          max:
            cpu: 4000m
            memory: 8192Mi
          scaling:
            enabled: false
            min: 1
            max: 2