profiles:
  - git://Logistics:metrics-profiles:main:dt-saas-atlas/us-walmart/dt-saas-mfc

deploy:
  stages:
    - name: prod-cell002
      helm:
        values:
          env:
            DYNATRACE_ENABLED: true
            JAVA_OPTS: >-
              -Xms6144m
              -Xmx6144m
              -XX:+UseParNewGC
              -XX:+UseConcMarkSweepGC
              -XX:NewSize=3072M
              -XX:MaxMetaspaceSize=256M
              -Dccm.configs.dir=/etc/config
              -Dscm.secrets.root.dir=/etc/secrets
              -Dspring.profiles.active=prod
              -Dtunr.enabled=true
              -Dtunr.configs.dir=/etc/config
              -Djsse.enableSNIExtension=true
              -Dplatform=wcnp
              -Druntime.context.appName=receiving-api
              -Druntime.context.environment=prod
              -Druntime.context.environmentType=prod
              -Druntime.context.environmentName=prod
              -Druntime.context.envProfile=prod
              -Druntime.context.system.property.override.enabled=true
              -Dspring.config.additional-location=/etc/secrets/receiving-secrets.properties
              -Dspring.config.use-legacy-processing=true
              -DdeploymentPrimaryRegion=scus
              -DdeploymentSite={{$.kittExec.currentCluster.site}}
              -Datlas-global-config-bootstrap=ccm
              -Dspring.main.allow-circular-references=true
              -DDATACENTER={{$.kittExec.currentCluster.zone}}
              -Dscm.snapshot.enabled=true
              -Dscm.root.dir=/tmp/scm
              -Dscm.print.summary.onchange=true
              -Dscm.print.detailed.summary=true
          metadata:
            annotations:
              strati.passthroughUris: '[{"Path":"^/swagger-ui.html$"},{"Path":"^/.*"}]'
              ccm.configVolumeMount: "/etc/config"
            labels:
              ccm.filter-redundant-properties: true
              ccm.server-delivery-api-version: v3
              ccm.serviceId: "receiving-api"
              ccm.serviceConfigVersion: "US-WM-STORE-PROD-1.0"
              isCcmEnabled: "true"
              ccm.deploymentContext: "${execCtx.currentStage.name.toLowerCase()}"
              ccm.apiVersion: "2.0"
              ccm.environmentType: prod
              ccm.environmentName: prod
              ccm.cellName: prod-cell002
              ccm.site: random
              ccm.node: "node"
              ccm.region: "{{$.kittExec.currentCluster.zone}}"
              ccm.zone: "{{$.kittExec.currentCluster.clusterId}}"
              ccm.deploymentSite: "{{$.kittExec.currentCluster.site}}"
              ccm.envProfile: prod
              ccm.environment: prod
              ccm.deploymentCountry: us
              ccm.deploymentRegionPair: scus-wus
              ccm.businessUnit: wm
              ccm.marketType: store
              ccm.applicationName: receiving-api
              wm.app: US-STORES-ATLAS-RECEIVING
              wm.env: prod-cell002
          volumeMounts:
            config-vol:
              mountPath: "/etc/config"
              meta:
                configMap:
                  name: "tunrconfig-${execCtx.currentStage.helm.values.global.metadata.labels['ccm.serviceId'].replaceAll('_', '-').toLowerCase()}-${execCtx.currentStage.helm.values.global.metadata.labels['ccm.serviceConfigVersion'].replaceAll('_', '-').toLowerCase()}-${execCtx.currentStage.helm.values.global.metadata.labels['ccm.deploymentContext'].contains('currentStage')?execCtx.currentStage.name.replaceAll('_', '-').toLowerCase():execCtx.currentStage.helm.values.global.metadata.labels['ccm.deploymentContext'].replaceAll('_', '-').toLowerCase()}"
          min:
            cpu: 2000m
            memory: 8192Mi
          max:
            cpu: 4000m
            memory: 8192Mi
          scaling:
            custom: true
            enabled: true
            min: 3
            max: 4
            prometheusQueries:
              http-events-per-second:
                queryContent: sum(rate(http_server_requests_seconds_count{mms_source="wcnp",service="{{$.kittExec.currentStage.releaseName}}",job="{{$.kittExec.currentStage.releaseName}}",namespace="{{$.kitt.deploy.namespace}}",uri!="/heartbeat",uri!="/prometheus"}[2m]))
                targetAverageValue: 1
