package com.walmart.move.nim.receiving.utils.constants;

public enum RetryTargetFlow {
  JMS_MESSAGE_PUBLISHING,
  DCFIN_PURCHASE_POSTING,
  DCFIN_PO_CLOSE,
  DCFIN_ADJUST_OR_VTR,
  GDM_PO_FINALIZE,
  INVENTORY_RECEIPT_RECEIVE_CORRECTION,
  INVENTORY_UPDATE_PO_DETAILS,
  INVENTORY_UPDATE_LOCATION,
  DECANT_MESSAGE_PUBLISH
}
