profiles:
  - git://Logistics:metrics-profiles:main:dt-saas-atlas/us-walmart/dt-saas-ambient

deploy:
  stages:
    - name: prod-amb-011
      helm:
        values:
          env:
            DYNATRACE_ENABLED: true
            JAVA_OPTS: >-
              -Xms6144m
              -Xmx6144m
              -XX:+UseParNewGC
              -XX:+UseConcMarkSweepGC
              -XX:NewSize=3072M
              -XX:MaxMetaspaceSize=256M
              -Djsse.enableSNIExtension=true
              -Druntime.context.environmentType=prod
              -Druntime.context.environment=PROD
              -Druntime.context.appName=receiving-api
              -Druntime.context.system.property.override.enabled=true
              -Dscm.snapshot.enabled=true
              -Dscm.root.dir=/tmp/scm
              -Dscm.print.summary.onchange=true
              -Dscm.print.detailed.summary=true
              -Dspring.config.use-legacy-processing=true
              -Dspring.config.additional-location=/etc/secrets/receiving-secrets.properties
              -DDATACENTER={{$.kittExec.currentCluster.zone}}
              -Dplatform=wcnp
              -DfacilityCountryCode=us
              -Dscm.scope.template=/prod/us/wm/amb/Cell011-USEast-USSouthCentral/{{$.kittExec.currentCluster.zone}}
              -Dspring.main.allow-circular-references=true
              -Dio.strati.RuntimeContext=io.strati.impl.runtime.context.RuntimeContextEnv
              -Dspring.main.allow-bean-definition-overriding=true
              -Dcom.walmart.platform.telemetry.structured.logging.enabled=true
          metadata:
            labels:
              wm.app: US-WM-CC-IMPORTS-ATLAS-RECEIVING
              wm.env: prod-cell011
            annotations:
              strati.passthroughUris: '[{"Path":"^/swagger-ui.html$"},{"Path":"^/.*"}]'
          min:
            cpu: 1000m
            memory: 8192Mi
          max:
            cpu: 4000m
            memory: 8192Mi
          scaling:
            enabled: true
            min: 2
            max: 6
            cpuPercent: 80
