profiles:
  - git://Logistics:metrics-profiles:main:dt-saas-atlas/us-walmart/dt-saas-common
  - git://Logistics:atlas-kitt-assets:main:deploy/us/wm/ambient/amb-deploy-v1

deploy:
  stages:
    - name: prod-001a
      helm:
        values:
          env:
            DYNATRACE_ENABLED: true
            atlas_deploymentContext: "PROD-US-WM-AMB-CELL001"
            atlas_deploymentSite: "{{$.kittExec.currentCluster.site}}"
            JAVA_OPTS: >-
              -Xms6144m
              -Xmx6144m
              -XX:+UseParNewGC
              -XX:+UseConcMarkSweepGC
              -XX:NewSize=3072M
              -XX:MaxMetaspaceSize=256M
              -Djsse.enableSNIExtension=true
              -Druntime.context.environmentType=prod
              -Druntime.context.environment=PROD
              -Druntime.context.appName=receiving-api
              -Druntime.context.system.property.override.enabled=true
              -Dscm.snapshot.enabled=true
              -Dscm.root.dir=/tmp/scm
              -Dscm.print.summary.onchange=true
              -Dscm.print.detailed.summary=true
              -Dspring.config.use-legacy-processing=true
              -Dspring.config.additional-location=/etc/secrets/receiving-secrets.properties
              -Dscm.scope.template=/prod/us/amb-cell001a-USSouthCentral-USWest/{{$.kittExec.currentCluster.site}}
              -DDATACENTER={{$.kittExec.currentCluster.zone}}
              -Dplatform=wcnp
              -DfacilityCountryCode=us
              -Dspring.main.allow-circular-references=true
              -DbusinessUnit=wm
              -DmarketType=amb
              -DdeploymentCountry=us
              -Denable_jms=true
              -Datlas-global-config-bootstrap=ccm
              -Dspring.main.allow-circular-references=true
              -Dspring.main.allow-bean-definition-overriding=true
          metadata:
            labels:
              strati.appkey: ATLASRECEIVING
              strati.env: prod
            annotations:
              strati.passthroughUris: '[{"Path":"^/swagger-ui.html$"},{"Path":"^/.*"}]'
          min:
            cpu: 800m
            memory: 8192Mi
          max:
            cpu: 4000m
            memory: 8192Mi
          scaling:
            enabled: false
            min: 3
            max: 3