deploy:
  stages:
    - name: prod-amb-001
      helm:
        values:
          env:
            DYNATRACE_ENABLED: true
            JAVA_OPTS: >-
              -Xms6144m
              -Xmx6144m
              -XX:+UseParNewGC
              -XX:+UseConcMarkSweepGC
              -XX:NewSize=3072M
              -XX:MaxMetaspaceSize=256M
              -Djsse.enableSNIExtension=true
              -Druntime.context.environmentType=prod
              -Druntime.context.environment=PROD
              -Druntime.context.appName=receiving-api
              -Druntime.context.system.property.override.enabled=true
              -Dscm.snapshot.enabled=true
              -Dscm.root.dir=/tmp/scm
              -Dscm.print.summary.onchange=true
              -Dscm.print.detailed.summary=true
              -Dspring.config.use-legacy-processing=true
              -Dspring.config.additional-location=/etc/secrets/receiving-secrets.properties
              -DDATACENTER={{$.kittExec.currentCluster.zone}}
              -Dplatform=wcnp
              -DfacilityCountryCode=us
              -DcellName=amb-cell001-USSouthCentral-USWest
              -Dspring.main.allow-circular-references=true
          metadata:
            labels:
              strati.appkey: ATLASRECEIVING
              strati.env: prod
            annotations:
              strati.passthroughUris: '[{"Path":"^/swagger-ui.html$"},{"Path":"^/.*"}]'
          min:
            cpu: 4000m
            memory: 8192Mi
          max:
            cpu: 4000m
            memory: 8192Mi
          scaling:
            enabled: false
            min: 3
            max: 3