SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECEIPT](
	[ID] [bigint] NOT NULL,
	[facilityCountryCode] [varchar](255) NULL,
	[facilityNum] [int] NULL,
	[CREATE_TS] [datetime2](7) NOT NULL,
	[CREATE_USER_ID] [varchar](32) NULL,
	[DELIVERY_NUMBER] [bigint] NOT NULL,
	[DOOR_NUMBER] [varchar](255) NULL,
	[EACH_QTY] [int] NULL,
	[PROBLEM_ID] [varchar](40) NULL,
	[PURCHASE_REFERENCE_LINE_NUMBER] [int] NOT NULL,
	[PURCHASE_REFERENCE_NUMBER] [bigint] NOT NULL,
	[QUANTITY] [int] NULL,
	[QUANTITY_UOM] [varchar](8) NULL,
	[VNPK_QTY] [int] NULL,
	[WHPK_QTY] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECEIPT] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [RECEIPT_TABLE_INDEX] ON [dbo].[RECEIPT]
(
	[PURCHASE_REFERENCE_NUMBER] ASC,
	[PURCHASE_REFERENCE_LINE_NUMBER] ASC,
	[DELIVERY_NUMBER] ASC,
	[facilityNum] ASC,
	[facilityCountryCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROBLEM](
	[ID] [bigint] NOT NULL,
	[facilityCountryCode] [varchar](255) NULL,
	[facilityNum] [int] NULL,
	[CREATE_TS] [datetime2](7) NULL,
	[CREATE_USER_ID] [varchar](32) NULL,
	[DELIVERY_NUMBER] [bigint] NOT NULL,
	[ISSUE_ID] [varchar](50) NOT NULL,
	[LAST_CHANGE_TS] [datetime2](7) NULL,
	[LAST_CHANGE_USER_ID] [varchar](32) NULL,
	[PROBLEM_STATUS] [varchar](32) NOT NULL,
	[PROBLEM_TAG_ID] [varchar](40) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROBLEM] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[PROBLEM] ADD  CONSTRAINT [UK_k5ipc20br8sx04rt5qjgt48a4] UNIQUE NONCLUSTERED 
(
	[PROBLEM_TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRINTJOB](
	[ID] [bigint] NOT NULL,
	[facilityCountryCode] [varchar](255) NULL,
	[facilityNum] [int] NULL,
	[COMPLETE_TS] [datetime2](7) NULL,
	[COMPLETED_LABEL_IDENTIFIER] [nvarchar](max) NULL,
	[CREATE_TS] [datetime2](7) NULL,
	[CREATE_USER_ID] [varchar](32) NOT NULL,
	[DELIVERY_NUMBER] [bigint] NOT NULL,
	[INSTRUCTION_ID] [bigint] NOT NULL,
	[LABEL_IDENTIFIER] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRINTJOB] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [PRINTJOB_TABLE_INDEX] ON [dbo].[PRINTJOB]
(
	[DELIVERY_NUMBER] ASC,
	[facilityNum] ASC,
	[facilityCountryCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JMS_EVENT_RETRY](
	[id] [bigint] NOT NULL,
	[RUNTIME_STATUS] [varchar](255) NULL,
	[FUTURE_PICKUP_TIME] [datetime2](7) NULL,
	[IS_ALERTED] [bit] NULL,
	[JMS_QUEUE_NAME] [varchar](255) NULL,
	[LAST_UPDATED_DATE] [datetime2](7) NULL,
	[REQUEST_PAYLOAD] [varchar](max) NULL,
	[RETRIES_COUNT] [bigint] NULL,
	[APPLICATION_TYPE] [varchar](255) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[JMS_EVENT_RETRY] ADD PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [EVENTRETRY_TABLE_INDEX] ON [dbo].[JMS_EVENT_RETRY]
(
	[RUNTIME_STATUS] ASC,
	[APPLICATION_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTAINER](
	[ID] [bigint] NOT NULL,
	[facilityCountryCode] [varchar](255) NULL,
	[facilityNum] [int] NULL,
	[COMPLETE_TS] [datetime2](7) NULL,
	[CONTAINER_STATUS] [varchar](20) NULL,
	[CONTAINER_TYPE] [varchar](20) NULL,
	[CREATE_TS] [datetime2](7) NULL,
	[CREATE_USER] [varchar](20) NULL,
	[CONTAINER_REUSABLE] [tinyint] NULL,
	[CONTAINER_SHIPPABLE] [tinyint] NULL,
	[CONTAINER_CUBE] [float] NULL,
	[CUBE_UOM] [varchar](2) NULL,
	[DELIVERY_NUMBER] [bigint] NOT NULL,
	[DESTINATION] [varchar](80) NULL,
	[FACILITY] [varchar](80) NULL,
	[INSTRUCTION_ID] [bigint] NULL,
	[INVENTORY_STATUS] [varchar](10) NULL,
	[LAST_CHANGED_TS] [datetime2](7) NULL,
	[LAST_CHANGED_USER] [varchar](20) NULL,
	[CONTAINER_LOCATION] [varchar](20) NULL,
	[MESSAGE_ID] [varchar](50) NOT NULL,
	[ORG_UNIT_ID] [varchar](20) NULL,
	[PARENT_TRACKING_ID] [varchar](40) NULL,
	[PUBLISH_TS] [datetime2](7) NULL,
	[TRACKING_ID] [varchar](40) NULL,
	[CONTAINER_WEIGHT] [float] NULL,
	[WEIGHT_UOM] [varchar](2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTAINER] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[CONTAINER] ADD  CONSTRAINT [UK_9sj85rkilen88u713i3a3y3nm] UNIQUE NONCLUSTERED 
(
	[TRACKING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [CONTAINER_TABLE_INDEX] ON [dbo].[CONTAINER]
(
	[DELIVERY_NUMBER] ASC,
	[facilityNum] ASC,
	[facilityCountryCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTAINER](
	[ID] [bigint] NOT NULL,
	[facilityCountryCode] [varchar](255) NULL,
	[facilityNum] [int] NULL,
	[COMPLETE_TS] [datetime2](7) NULL,
	[CONTAINER_STATUS] [varchar](20) NULL,
	[CONTAINER_TYPE] [varchar](20) NULL,
	[CREATE_TS] [datetime2](7) NULL,
	[CREATE_USER] [varchar](20) NULL,
	[CONTAINER_REUSABLE] [tinyint] NULL,
	[CONTAINER_SHIPPABLE] [tinyint] NULL,
	[CONTAINER_CUBE] [float] NULL,
	[CUBE_UOM] [varchar](2) NULL,
	[DELIVERY_NUMBER] [bigint] NOT NULL,
	[DESTINATION] [varchar](80) NULL,
	[FACILITY] [varchar](80) NULL,
	[INSTRUCTION_ID] [bigint] NULL,
	[INVENTORY_STATUS] [varchar](10) NULL,
	[LAST_CHANGED_TS] [datetime2](7) NULL,
	[LAST_CHANGED_USER] [varchar](20) NULL,
	[CONTAINER_LOCATION] [varchar](20) NULL,
	[MESSAGE_ID] [varchar](50) NOT NULL,
	[ORG_UNIT_ID] [varchar](20) NULL,
	[PARENT_TRACKING_ID] [varchar](40) NULL,
	[PUBLISH_TS] [datetime2](7) NULL,
	[TRACKING_ID] [varchar](40) NULL,
	[CONTAINER_WEIGHT] [float] NULL,
	[WEIGHT_UOM] [varchar](2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTAINER] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[CONTAINER] ADD  CONSTRAINT [UK_9sj85rkilen88u713i3a3y3nm] UNIQUE NONCLUSTERED 
(
	[TRACKING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [CONTAINER_TABLE_INDEX] ON [dbo].[CONTAINER]
(
	[DELIVERY_NUMBER] ASC,
	[facilityNum] ASC,
	[facilityCountryCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTAINER_ITEM](
	[CONTAINER_ITEM_ID] [bigint] NOT NULL,
	[facilityCountryCode] [varchar](255) NULL,
	[facilityNum] [int] NULL,
	[BASE_DIVISION_CODE] [varchar](8) NULL,
	[DEPT_NUMBER] [int] NULL,
	[DESCRIPTION] [varchar](80) NULL,
	[DISTRIBUTIONS] [nvarchar](max) NULL,
	[FINANCIAL_REPORTING_GROUP_CODE] [varchar](8) NULL,
	[GTIN] [varchar](20) NULL,
	[INBOUND_CHANNEL_METHOD] [varchar](15) NULL,
	[ITEM_NUMBER] [bigint] NULL,
	[OUTBOUND_CHANNEL_METHOD] [varchar](15) NULL,
	[PO_DEPT_NUMBER] [varchar](10) NULL,
	[PURCHASE_COMPANY_ID] [int] NULL,
	[PURHCASE_REFERENCE_LINE_NUMBER] [int] NULL,
	[PURCHASE_REFERENCE_NUMBER] [bigint] NULL,
	[QUANTITY] [int] NULL,
	[QUANTITY_UOM] [varchar](2) NULL,
	[ROTATE_DATE] [datetime2](7) NULL,
	[SECONDARY_DESCRIPTION] [varchar](80) NULL,
	[TOTAL_PURCHASER_REFERENCE_QTY] [int] NULL,
	[TRACKING_ID] [varchar](40) NOT NULL,
	[VENDOR_GS_128] [varchar](32) NULL,
	[VENDOR_PACK_COST] [float] NULL,
	[VNPK_QTY] [int] NULL,
	[VNPK_WEIGHT_QTY] [float] NULL,
	[VNPK_WEIGHT_QTY_UOM] [varchar](4) NULL,
	[VNPK_CUBE_QTY] [float] NULL,
	[VNPK_CUBE_QTY_UOM] [varchar](4) NULL,
	[WHPK_QTY] [int] NULL,
	[WHPK_SELL] [float] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTAINER_ITEM] ADD PRIMARY KEY CLUSTERED 
(
	[CONTAINER_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [CONTAINERITEM_TABLE_INDEX] ON [dbo].[CONTAINER_ITEM]
(
	[PURCHASE_REFERENCE_NUMBER] ASC,
	[PURHCASE_REFERENCE_LINE_NUMBER] ASC,
	[TRACKING_ID] ASC,
	[facilityNum] ASC,
	[facilityCountryCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE TABLE [dbo].[shedlock](
	[name] [varchar](64) NOT NULL,
	[lock_until] [datetime] NULL,
	[locked_at] [datetime] NULL,
	[locked_by] [varchar](255) NOT NULL,
 CONSTRAINT [PK_shedlock] PRIMARY KEY CLUSTERED
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


