DROP TABLE [dbo].[CONTAINER_ITEM]
GO
DROP TABLE [dbo].[CONTAINER]
GO
DROP TABLE [dbo].[RECEIPT]
GO
DROP TABLE [dbo].[PRINTJOB]
GO
DROP TABLE [dbo].[BATCH_MIGRATION]
GO
DROP TABLE [dbo].[MIGRATED_DATA_INFO]
GO
DROP TABLE [dbo].[JMS_EVENT_RETRY]
GO
DROP TABLE [dbo].[CONTAINER]
GO
DROP TABLE [dbo].[PROBLEM]
GO
DROP TABLE [dbo].[INSTRUCTION]
GO