DROP TABLE [ENDGAME_UPC_DESTINATION]

DROP SEQUENCE  IF EXISTS  ENDGAME_UPC_SLOTTING_SEQUENCE;

DROP TABLE [ENDGAME_LABEL_DETAILS]

DROP SEQUENCE  IF EXISTS  ENDGAME_LABEL_DETAILS_SEQUENCE;

DROP TABLE [ENDGAME_DELIVERY_METADATA]

DROP SEQUENCE  IF EXISTS  ENDGAME_DELIVERY_METADATA_SEQUENCE;

DROP TABLE [RECEIVING_COUNTER]

DROP SEQUENCE  IF EXISTS RECEIVING_COUNTER_SEQUENCE;

