CREATE INDEX CONTAINER_BY_TRACKINGID ON dbo.CONTAINER (TRACKING_ID, facilityNum, facilityCountryCode);
CREATE INDEX CONTAINER_BY_PARENT_TRACKINGID ON dbo.CONTAINER (PARENT_TRACKING_ID, facilityNum, facilityCountryCode);
CREATE INDEX CONTAINER_BY_DELIVERY ON dbo.CONTAINER (DELIVERY_NUMBER, facilityNum, facilityCountryCode);
CREATE INDEX CONTAINER_BY_INSTRUCTION ON dbo.CONTAINER (INSTRUCTION_ID, facilityNum, facilityCountryCode);

CREATE INDEX CONTAINER_ITEM_BY_TRACKINGID ON dbo.CONTAINER_ITEM (TRACKING_ID, facilityNum, facilityCountryCode);
CREATE INDEX CONTAINER_ITEM_BY_TRACKINGIDANDPO ON dbo.CONTAINER_ITEM (TRACKING_ID, PURCHASE_REFERENCE_NUMBER, PURCHASE_REFERENCE_LINE_NUMBER, facilityNum, facilityCountryCode);

CREATE INDEX INSTRUCTION_BY_DELIVERY_NUMBER ON dbo.INSTRUCTION (DELIVERY_NUMBER, facilityNum, facilityCountryCode);
CREATE INDEX INSTRUCTION_BY_MESSAGEID ON dbo.INSTRUCTION (MESSAGE_ID, facilityNum, facilityCountryCode);
CREATE INDEX INSTRUCTION_BY_DEL_CTS_CODE ON dbo.INSTRUCTION (DELIVERY_NUMBER, COMPLETE_TS, INSTRUCTION_CODE, facilityNum, facilityCountryCode);
CREATE INDEX INSTRUCTION_BY_DEL_PROB_CODE ON dbo.INSTRUCTION (DELIVERY_NUMBER,PROBLEM_TAG_ID, INSTRUCTION_CODE,facilityNum, facilityCountryCode);
CREATE INDEX INSTRUCTION_BY_DEL_CODE ON dbo.INSTRUCTION (DELIVERY_NUMBER, INSTRUCTION_CODE,facilityNum, facilityCountryCode);
CREATE INDEX INSTRUCTION_BY_PROB_CODE ON dbo.INSTRUCTION (PROBLEM_TAG_ID, INSTRUCTION_CODE,facilityNum, facilityCountryCode);

CREATE INDEX RECEIPT_BY_DELIVERY ON dbo.RECEIPT (DELIVERY_NUMBER, facilityNum, facilityCountryCode);
CREATE INDEX RECEIPT_BY_PROB ON dbo.RECEIPT (PROBLEM_ID, facilityNum, facilityCountryCode);
CREATE INDEX RECEIPT_BY_DELIVERY_PO ON dbo.RECEIPT (DELIVERY_NUMBER, PURCHASE_REFERENCE_NUMBER, PURCHASE_REFERENCE_LINE_NUMBER,facilityNum, facilityCountryCode);
CREATE INDEX RECEIPT_BY_PO ON dbo.RECEIPT (PURCHASE_REFERENCE_NUMBER, PURCHASE_REFERENCE_LINE_NUMBER,facilityNum, facilityCountryCode);

CREATE INDEX PROBLEM_BY_TAG ON dbo.PROBLEM (PROBLEM_TAG_ID, facilityNum, facilityCountryCode);

CREATE INDEX PRINT_BY_DELIVERY ON dbo.PRINTJOB (DELIVERY_NUMBER, facilityNum, facilityCountryCode);
CREATE INDEX PRINT_BY_INSTRUCTION ON dbo.PRINTJOB (INSTRUCTION_ID, facilityNum, facilityCountryCode);

