CREATE INDEX INSTRUCTION_TABLE_INDEX
ON dbo.INSTRUCTION (MESSAGE_ID, DELIVERY_NUMBER, facilityNum, facilityCountryCode,GTIN);

CREATE INDEX RECEIPT_TABLE_INDEX
ON dbo.RECEIPT (PURCHASE_REFERENCE_NUMBER,PURCHASE_REFERENCE_LINE_NUMBER, DELIVERY_NUMBER, facilityNum, facilityCountryCode);

CREATE INDEX CONTAINER_TABLE_INDEX
ON dbo.CONTAINER (DELIVERY_NUMBER,TRACKING_ID, PARENT_TRACKING_ID, facilityNum, facilityCountryCode);

CREATE INDEX CONTAINERITEM_TABLE_INDEX
ON dbo.CONTAINER_ITEM (PURCHASE_REFERENCE_NUMBER, PURCHASE_REFERENCE_LINE_NUMBER, TRACKING_ID, facilityNum, facilityCountryCode);

CREATE INDEX EVENTRETRY_TABLE_INDEX
ON dbo.JMS_EVENT_RETRY (RUNTIME_STATUS,APPLICATION_TYPE);

CREATE INDEX PRINTJOB_TABLE_INDEX
ON dbo.PRINTJOB (DELIVERY_NUMBER, facilityNum, facilityCountryCode);