package com.walmart.move.nim.receiving.acc.constants;

import java.util.HashMap;
import java.util.Map;

public final class LabelingConstants {

  private LabelingConstants() {}

  public static final String CLIENT_ID = "RCV-ACL-PRE";
  public static final String CASE_LPN_FORMAT = "case_lpn_format";
  public static final String LABEL_ID_PLACEHOLDER = "=LPN=";
  public static final String LABEL_DATE = "LABELDATE";
  public static final String LABEL_DATE_PLACEHOLDER = "=LABELTIMESTAMP=";
  public static final String LPN = "LPN";
  public static final String FULLUSERID = "FULLUSERID";
  public static final String FULLUSERID_SYS_ACL = "SYS-ACL";
  public static final String HAZMAT = "HAZMAT";
  public static final String HAZMAT_H = "H";
  public static final String POCODE = "POCODE";
  public static final String VENDORID = "VENDORID";
  public static final String COLOR = "COLOR";
  public static final String QTY = "QTY";
  public static final String DEPT = "DEPT";
  public static final String CPQTY = "CPQTY";
  public static final String DESC1 = "DESC1";
  public static final String DESC2 = "DESC2";
  public static final String PACKTYPE = "PACKTYPE";
  public static final String PACKTYPE_CP = "CP";
  public static final String PACKTYPE_BP = "BP";
  public static final String SIZE = "SIZE";
  public static final String DSDC = "DSDC";
  public static final String POEVENT = "POEVENT";
  public static final String EVENTCHAR = "EVENTCHAR";
  public static final String STOREZONE = "STOREZONE";
  public static final String REPRINT = "REPRINT";
  public static final String ITEM = "ITEM";
  public static final String PRINTER = "PRINTER";
  public static final String POLINE = "POLINE";
  public static final String DESTINATION = "DESTINATION";
  public static final String CHANNEL = "CHANNEL";
  public static final String CHANNEL_VAL = "DIST";
  public static final String UPCBAR = "UPCBAR";
  public static final String PACK = "PACK";
  public static final String PO = "PO";
  public static final String ORIGIN = "ORIGIN";
  public static final String DELIVERY = "DELIVERY";
  public static final String DOOR = "DOOR";
  public static final String EMPTY_STRING = "";

  public static final Map<Integer, String> STORE_MAP = new HashMap<>();

  static {
    STORE_MAP.put(0, "B");
    STORE_MAP.put(32, "B");
    STORE_MAP.put(38, "E");
    STORE_MAP.put(73, "E");
    STORE_MAP.put(83, "F");
    STORE_MAP.put(90, "F");
    STORE_MAP.put(91, "F");
    STORE_MAP.put(96, "F");
    STORE_MAP.put(98, "F");
    STORE_MAP.put(49, "E");
    STORE_MAP.put(79, "B");
    STORE_MAP.put(71, "A");
    STORE_MAP.put(74, "A");
    STORE_MAP.put(82, "F");
    STORE_MAP.put(84, "E");
    STORE_MAP.put(85, "D");
    STORE_MAP.put(87, "D");
    STORE_MAP.put(92, "F");
    STORE_MAP.put(95, "F");
    STORE_MAP.put(99, "D");
    STORE_MAP.put(1, "F");
    STORE_MAP.put(2, "E");
    STORE_MAP.put(3, "E");
    STORE_MAP.put(4, "C");
    STORE_MAP.put(5, "D");
    STORE_MAP.put(6, "D");
    STORE_MAP.put(7, "C");
    STORE_MAP.put(8, "D");
    STORE_MAP.put(9, "C");
    STORE_MAP.put(10, "A");
    STORE_MAP.put(11, "A");
    STORE_MAP.put(12, "A");
    STORE_MAP.put(13, "C");
    STORE_MAP.put(14, "A");
    STORE_MAP.put(15, "A");
    STORE_MAP.put(16, "D");
    STORE_MAP.put(17, "A");
    STORE_MAP.put(18, "A");
    STORE_MAP.put(19, "D");
    STORE_MAP.put(20, "E");
    STORE_MAP.put(21, "E");
    STORE_MAP.put(22, "E");
    STORE_MAP.put(23, "B");
    STORE_MAP.put(24, "B");
    STORE_MAP.put(25, "B");
    STORE_MAP.put(26, "B");
    STORE_MAP.put(27, "B");
    STORE_MAP.put(28, "B");
    STORE_MAP.put(29, "B");
    STORE_MAP.put(30, "B");
    STORE_MAP.put(31, "B");
    STORE_MAP.put(33, "B");
    STORE_MAP.put(34, "B");
    STORE_MAP.put(35, "B");
    STORE_MAP.put(36, "B");
    STORE_MAP.put(40, "E");
    STORE_MAP.put(41, "D");
    STORE_MAP.put(42, "A");
    STORE_MAP.put(43, "C");
    STORE_MAP.put(44, "D");
    STORE_MAP.put(45, "C");
    STORE_MAP.put(46, "E");
    STORE_MAP.put(47, "E");
    STORE_MAP.put(48, "C");
    STORE_MAP.put(51, "C");
    STORE_MAP.put(52, "D");
    STORE_MAP.put(53, "E");
    STORE_MAP.put(54, "E");
    STORE_MAP.put(55, "D");
    STORE_MAP.put(56, "D");
    STORE_MAP.put(57, "C");
    STORE_MAP.put(59, "E");
    STORE_MAP.put(67, "E");
    STORE_MAP.put(72, "D");
    STORE_MAP.put(78, "B");
  }
}
